name: Docker Image CI

on:
  push:
     branches: ["main"]
  pull_request:
     branches: ["main"]

permissions:
  contents: read

jobs:
  BuildAndValidate:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Install ShellCheck
        run: |
          sudo apt-get update
          sudo apt-get install -y shellcheck

      - name: Validate Bash scripts
        run: |
          for script in scripts/*.sh; do
            echo "Checking $script"
            bash -n "$script"

            echo "ShellChecking script"
            shellcheck -x "$script"
          done

      - name: Build Docker image
        run: docker build -t infra-lab .

      - name: Run Docker container
        run: docker run -d --name flask-app -p 5000:5000 infra-lab

      - name: Check container health
        run: |
          echo "Testing /health"

          for i in {1..20}; do
            if curl -fsS "http://localhost:5000/health"; then
              echo "Endpoint healthy"
              exit 0
            else
              echo "Endpoint unhealthy"
              sleep 1
            fi
          done

          echo "Unsuccessful health test"
          docker logs flask-app
          exit 1

      - name: Cleanup
        if: always()
        run: |
          docker stop flask-app || true
          docker rm flask-app || true
